### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain'

### ISSUE THREAD

**Issue by barahona2684** [jfqd/redmine_helpdesk#130]
**ERROR**
-----------------------
redmine-3.4.4
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
Rails 5.1.4
-----------------------

```
rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for Journal (call 'Journal.connection' to establish a connection):Class
Did you mean?  alias_method
[...]/plugins/redmine_helpdesk/lib/journal_patch.rb:7:in `block in included'
[...]/plugins/redmine_helpdesk/lib/journal_patch.rb:6:in `class_eval'
[...]/plugins/redmine_helpdesk/lib/journal_patch.rb:6:in `included'
[...]/plugins/redmine_helpdesk/lib/journal_patch.rb:39:in `include'
[...]/plugins/redmine_helpdesk/lib/journal_patch.rb:39:in `<top (required)>'
[...]/plugins/redmine_helpdesk/init.rb:4:in `<top (required)>'
[...]/lib/redmine/plugin.rb:155:in `block in load'
[...]/lib/redmine/plugin.rb:146:in `each'
[...]/lib/redmine/plugin.rb:146:in `load'
[...]/config/initializers/30-redmine.rb:21:in `<top (required)>'
[...]/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by jfqd** [comment]
There is no version of the plugin for redmine-3.4.4. You may try out redmine-4.0.x.
