### ISSUE TITLE
When I try to update a child ticket associated with a particular parent ticket, I will get a 500 error.

### ISSUE THREAD

**Issue by leecholho** [jfqd/redmine_helpdesk#167]
hellow.
I created a new ticket and tried to make a particular ticket the parent ticket, but I also got a 500 error.
That particular ticket has 156 child tickets.

redmine information is below.
```
Environment:
  Redmine version                2.6.8.stable
  Ruby version                   2.0.0-p648 (2015-12-16) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  redmine_backlogs               v1.0.6
  redmine_scm                    0.5.0b
```
error message is below.
```
Completed 500 Internal Server Error in 191.4ms

TypeError (no implicit conversion of Symbol into Integer):
  app/models/issue.rb:165:in `create_or_update'
  app/models/issue.rb:1422:in `recalculate_attributes_for'
  app/models/issue.rb:1384:in `update_parent_attributes'
  app/models/issue.rb:165:in `create_or_update'
  app/controllers/issues_controller.rb:481:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:469:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:188:in `update'
```

**Comment by jfqd** [comment]
Redmine 2.6.8. is way too old with lots of cves. You should use a recent version, like 4.2.3!
