### ISSUE TITLE
 failed to load command: rake

### ISSUE THREAD

**Issue by othin1** [jfqd/redmine_helpdesk#170]
Hi all,i've tryied to install this plugin on my docker redmine (v 5.0) but when i use the command:
**bundle exec rake redmine:plugins:migrate RAILS_ENV=production** i see this error:

```
bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/rubygems_integration.rb:319:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/rubygems_integration.rb:347:in `block in replace_bin_path'
        from /usr/local/bundle/bin/rake:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'

```

gem -v
3.3.12

bundle -v
Bundler version 2.3.12

I've try to remove Gemfile.lock and reinstall the bundler but nothing, anyone can help me?
Thanks

**Comment by stefanoglv** [comment]
Hi, you can find a Pull request for Compatibility with Redmine 5.0.
It works at 90%, i have only a problem with Re: mail from anonymous user... i'm trying to understand, i think should be a compatibility bug
