### ISSUE TITLE
Re:  don't work

### ISSUE THREAD

**Issue by stefanoglv** [jfqd/redmine_helpdesk#171]
if an anonymous user reply something the task goes il loop here:

/redmine/plugins/redmine_helpdesk/lib/redmine_helpdesk_mail_handler_patch.rb:105:in `receive_issue_reply_with_helpdesk'

Full trace:
/opt/bitnami/redmine/plugins/redmine_helpdesk/lib/redmine_helpdesk_mail_handler_patch.rb:105:in `receive_issue_reply_with_helpdesk'
...many lines like these....
/bitnami/redmine/plugins/redmine_helpdesk/lib/redmine_helpdesk_mail_handler_patch.rb:105:in `receive_issue_reply_with_helpdesk'
/opt/bitnami/redmine/app/models/mail_handler.rb:155:in `dispatch'
/opt/bitnami/redmine/app/models/mail_handler.rb:139:in `receive'
/opt/bitnami/redmine/app/models/mail_handler.rb:49:in `block in receive'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:205:in `instrument'
/opt/bitnami/redmine/app/models/mail_handler.rb:46:in `receive'
/opt/bitnami/redmine/app/models/mail_handler.rb:55:in `safe_receive'
/opt/bitnami/redmine/lib/redmine/pop3.rb:53:in `block (2 levels) in check'
/opt/bitnami/ruby/lib/ruby/3.0.0/net/pop.rb:666:in `each'
/opt/bitnami/ruby/lib/ruby/3.0.0/net/pop.rb:666:in `each_mail'
/opt/bitnami/redmine/lib/redmine/pop3.rb:50:in `block in check'
/opt/bitnami/ruby/lib/ruby/3.0.0/net/pop.rb:531:in `start'
/opt/bitnami/redmine/lib/redmine/pop3.rb:45:in `check'
/opt/bitnami/redmine/lib/tasks/email.rake:152:in `block (4 levels) in <top (required)>'
/opt/bitnami/redmine/app/models/mailer.rb:648:in `with_synched_deliveries'
/opt/bitnami/redmine/lib/tasks/email.rake:151:in `block (3 levels) in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/bitnami/redmine/bin/rake:27:in `load'
/opt/bitnami/redmine/bin/rake:27:in `<main>'
Tasks: TOP => redmine:email:receive_pop3

**Comment by stefanoglv** [comment]
i'm working on a v5.0.1 redmine
