### ISSUE TITLE
Issue when installing on Redmine 3.1

### ISSUE THREAD

**Issue by adubreuiltk** [jfqd/redmine_helpdesk#98]
Here is the log:

```
Migrating redmine_helpdesk (Redmine helpdesk plugin)...
== 6 AppendFooterToFirstReply: migrating ======================================
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `id' for nil:NilClass/usr/share/redmine-3.1.0/plugins/redmine_helpdesk/db/migrate/006_append_footer_to_first_reply.rb:6:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:568:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:1042:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/usr/share/redmine-3.1.0/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine-3.1.0/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine-3.1.0/lib/redmine/plugin.rb:467:in `block in migrate'
/usr/share/redmine-3.1.0/lib/redmine/plugin.rb:466:in `each'
/usr/share/redmine-3.1.0/lib/redmine/plugin.rb:466:in `migrate'
/usr/share/redmine-3.1.0/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by Sh4d0wF1gh7** [comment]
hello,
currently i get same error? what was the solution?

**Comment by KMVSoft** [comment]
hello,
currently i get same error? what was the solution?
